### ISSUE TITLE
Possible but emitting duplicate events 

### ISSUE THREAD

**Issue by dtyree-spyderbat** [spyderbat/event-forwarder#5]
It appears that the startup sequence allows for duplicate logs to be emitted if more than 655360 events are in the logs read at startup, and if the logs are read in an order which loads them newest to oldest.

**Comment by spyder-jeff** [comment]
+also add info on startup about state restoration

**Comment by spyder-jeff** [comment]
https://github.com/spyderbat/event-forwarder/pull/13
